spring:
  application:
    name: DocumentService

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/document_service_db}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

  jpa:
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:user}
  secret-key: ${MINIO_SECRET_KEY:password}

document:
  template-bucket: ${TEMPLATE_BUCKET:templates}
  document-bucket: ${DOCUMENT_BUCKET:documents}
  placeholder-regex: ${PLACEHOLDER_REGEX:\{\{(\w+):(\w+)\}\}}

work-acceptance-act:
  list-delimiter: ${WORK_ACCEPTANCE_ACT_LIST_DELIMITER:;}
  template-name: ${WORK_ACCEPTANCE_ACT_TEMPLATE_NAME:WORK_ACCEPTANCE_ACT}
  name-format: ${WORK_ACCEPTANCE_ACT_NAME_FORMAT:Акт_сдачи-приёмки_работ_№%s.docx}